In [1]:
import numpy as np

In [3]:
array_1d=np.array([1,2,3,4,5])

array_1d

array([1, 2, 3, 4, 5])

In [7]:
array_2d=np.array([[1,2,3,4,5],[34,45,67,78,0]])

array_2d # note:length needs to be same otherwise error

array([[ 1,  2,  3,  4,  5],
       [34, 45, 67, 78,  0]])

In [8]:
#creating a 2d array of zeros

zeros_arr=np.zeros((3,4))
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#creating 1d array of ones

ones_arr=np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [10]:
#creating an array woth values ranging from 0-9

range_arr=np.arange(10)
range_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#creating an array with 5 evenly spaced values between 0 and 1

linspace_arr= np.linspace(0,1,5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
#checking shape

array_2d.shape

(2, 5)

In [16]:
#checking size
array_2d.size

10

In [17]:
#checking type
array_2d.dtype

dtype('int64')

In [18]:
#indexing= accessing & manipulating arrays

#accessing the third element
array_1d[2]

np.int64(3)

In [19]:
#accessing the second-last element
array_1d[-2]

np.int64(4)

In [20]:
#accessing elements from a 2d array at row1 and col2
array_2d[1,2]

np.int64(67)

In [21]:
#accessing the second row
array_2d[1]

array([34, 45, 67, 78,  0])

In [23]:
#accessing the first col
array_2d[:,1]

array([ 2, 45])

In [24]:
#boolean indexing to select elements greater than 3
boolean_index=array_2d[array_2d >3]
boolean_index

array([ 4,  5, 34, 45, 67, 78])

In [27]:
#selecting particular elements using integer array indexing
array_2d[1,[0,2]] #here it means 1 denotes the row number which here it is second row and then fromt hat row select 0th and 2th element

array([34, 67])

In [30]:
#Slicing

#slicing elements from index 1 to 3
slice_1d=array_1d[1:4]  # it is not inclusive of 4(i.e. last index)
slice_1d

array([2, 3, 4])

In [32]:
#slicing elements from 0-4 index with a step of 2
slice_step_1d=array_1d[0:5:2]
slice_step_1d

array([1, 3, 5])

In [33]:
#slicing a sub-array from the first two rows and cols

slice_2d=array_2d[:2,:2]
slice_2d

array([[ 1,  2],
       [34, 45]])

In [36]:
#slicing the first row
rows_2d=array_2d[:1]
rows_2d

array([[1, 2, 3, 4, 5]])

In [37]:
#slicing the last column
last_col_2d=array_2d[:,-1]
last_col_2d

array([5, 0])

In [39]:
#slicing every other row
step_rows_2d=array_2d[::2]
step_rows_2d

array([[1, 2, 3, 4, 5]])

In [40]:
#slicing every other col
step_cols_2d=array_2d[:,::2]
step_cols_2d

array([[ 1,  3,  5],
       [34, 67,  0]])